### PR TITLE
Add ability to enable customToolbar

### LINKED ISSUE #20: Customize zoom level
I can't find any props that allow changing zoom level.

### PR DESCRIPTION
**Pull request by hichemfantar**
closes #20 and #22

### CODE REVIEW

**Review by Shenato — CHANGES_REQUESTED** [review]
As it is right now this PR would break how the SVGViewer provided with this package was supposed to look, it was supposed to be an opinionated minimalist component for viewing your bracket out of the box without needing to override away functionality you didn't want, and being able to extend it as much as sanely possible.

At some point, writing your own SVGViewer would be the better option, either using `react-svg-pan-zoom` package or some other means the consumer prefers.

I do however think that it's definitely a missed opportunity to allow customizing the toolbar and I'm glad you spotted this, therefore I would suggest you edit your PR to allow for that while also maintaining the initial goal of this SVGViewer component.
 
First, I would recommend you consume `customToolbar` like so from the props
```jsx
const SvgViewer = ({
  height = 500,
  width = 500,
  bracketWidth,
  bracketHeight,
  children,
  startAt = [0, 0],
  scaleFactor = 1.1,
  customToolbar,
  ...rest
}) => {
```

and bring back line 59 and have it as an option to customize the toolbar otherwise to not render one like so
```jsx
customToolbar={customToolbar ?? (() => <></>)}
```

That way we bring customizability without sacrificing the minimalism of the out of the box experience of the SVGViewer.

I'll be happy to merge this in afterwards 👍

**Comment by hichemfantar** [comment]
Does this mean I'm forced to create a custom toolbar when I want to activate it?
What if the developer is satisfied with the default toolbar and simply wants to activate it?
I believe the option to use the default toolbar should be possible.
I believe this PR is a breaking change considering it changes the default behavior of the library. Perhaps a simple major version bump alone with this PR is enough.
Would love to hear your opinion on this.

**Comment by Shenato** [comment]
> Does this mean I'm forced to create a custom toolbar when I want to activate it?
> What if the developer is satisfied with the default toolbar and simply wants to activate it?

In that case the developer can use the peerDependency `react-svg-pan-zoom` directly and write their own SvgViewer. this library's focus is the bracket component and the SvgViewer is meant to be a minimal solution to rendering it without any bloat.

> I believe the option to use the default toolbar should be possible.

I agree with you, however I don't believe it should be the default option, and I don't believe this library should concern itself with solving all the possible user experience scenarios for the SvgViewer.



As I've said earlier the SvgViewer provided with the library aims to be an opinionated minimalistic viewer with sensible defaults to allow it to fit most use-cases, the aim is to serve most developers who don't want a default toolbar that clashes with their own design language when they implement this library in their UI.

If you like the default `react-svg-pan-zoom`'s toolbar and you do not agree with this opinion, you can write your own simple viewer and use that.

**Comment by Shenato** [comment]
I've implemented the suggested solution in this PR #39

**Comment by Shenato** [comment]
Closing this pull request as I've implemented this in the other PR #39. Feel free to re-open the discussion if that's not what you were looking for.

**Pull request closed without merging**
